PLATFORM = 'flapper'
USE_OPEN_LOOP = False

# Attitude PID definitions
ROLL_KP = 10
ROLL_KI = 0
ROLL_KD = 0.2
ROLL_KFF = 0
ROLL_INTEGRATION_LIMIT = 20.0

PITCH_KP = 13
PITCH_KI = 0
PITCH_KD = 1
PITCH_KFF = 0
PITCH_INTEGRATION_LIMIT = 20.0

YAW_KP = 8
YAW_KI = 0
YAW_KD = 0.35
YAW_KFF = 0
YAW_INTEGRATION_LIMIT = 360.0

# Rate PID definitions
ROLLRATE_KP = 50
ROLLRATE_KI = 0
ROLLRATE_KD = 0
ROLLRATE_KFF = 0
OMX_FILT_CUT = 20
ROLLRATE_INTEGRATION_LIMIT = 33.3

PITCHRATE_KP = 50
PITCHRATE_KI = 0
PITCHRATE_KD = 0
PITCHRATE_KFF = 0
OMY_FILT_CUT = 20
PITCHRATE_INTEGRATION_LIMIT = 33.3

YAWRATE_KP = 80
YAWRATE_KI = 0
YAWRATE_KD = 0
YAWRATE_KFF = 220
OMZ_FILT_CUT = 5
YAWRATE_INTEGRATION_LIMIT = 166.7
YAW_MAX_DELTA = 30.0


# mass moments of inertia
MMOI_WITH_WINGS = {"Ixx": 5.6e-4, "Iyy": 3.4e-4, "Izz": 3.6e-4}  # kg/m^2

MMOI_WITH_WINGS_XY = {"Ixx": 5.6e-4, "Iyy": 3.4e-4, "Izz": 2.8e-4}  # kg/m^2 # with wings oriented in XY plane

MMOI_NO_WINGS = {"Ixx": 3.1e-4, "Iyy": 3.0e-4, "Izz": 2.7e-4}  # kg/m^2

M_WINGS = 0.1026  # kg

M_NO_WINGS = 0.0943  # kg

# Transfer function values
TAU_FLAPPING = 0.0796

OMEGA_DIHEDRAL = 40

ZETA_DIHEDRAL = 0.634

OMEGA_YAW = None

ZETA_YAW = None
